app:
  name: auth
db:
  adapter: postgresql
  host: localhost
  port: 5432
  user: postgres
  url: <%= ENV['AUTH_DATABASE_URL'] %>
  password: notsecure
rabbitmq:
  host: <%= ENV['AUTH_RABBITMQ_HOST'] %>
  username: <%= ENV['AUTH_RABBITMQ_USER'] %>
  password: <%= ENV['AUTH_RABBITMQ_PASSWORD'] %>
  consumer_pool: 10
application:
  secret: "1072aa78-b9d5-4d78-a134-f97c3d37258d"
logger:
  path: log/app.log
  level: info