rabbitmq:
  host: <%= ENV.fetch('AUTH_RABBITMQ_HOST') %>
  username: <%= ENV.fetch('AUTH_RABBITMQ_USER') %>
  password: <%= ENV.fetch('AUTH_RABBITMQ_PASSWORD') %>
db:
  database: auth_microservice_production
  url: <%= ENV.fetch('AUTH_DATABASE_URL') %>